const { spoiler } = require("@discordjs/builders");

const RandomWordsArray = [
    "Gorilla",
    "Hash",
    "LSD",
    "E",
    "Krokstrand",
    "Dalaberg",
    "NNN",
    "Trögsex",
    "Florent",
    "Ganton",
    "Lukas",
    "David",
    "Körner",
    "Tim",
    "Sebbe",
    "Lowe",
    "Jacob",
    "Moses",
    "Högberg",
    "David",
    "Orust",
    "Forshälla",
    "Ljungskile",
    "Porrberoende",
    "Sinclair",
    "David",
    "Al qaida",
    "Roman",
    "Folkomröstning",
    "Torktumlare",
    "Cykelpump",
    "Nackspärr",
    "Tjuv",
    "Knäckebröd",
    "Plättar",
    "Kastanj",
    "Kassler",
    "Skådespelare",
    "Avundsjuka",
    "Diktator",
    "Pärla",
    "Puls",
    "Åskledare",
    "Gummi",
    "Plast",
    "Charlotte Kalla",
    "Högaffel",
    "Trädgård",
    "Daggmask",
    "Rullgardin",
    "Pannlampa",
    "Pilot",
    "Balettdansös",
    "Fiskdamm",
    "Tango",
    "Provrör",
    "Soppatorsk",
    "Tjuv",
    "Nyckel",
    "Pojke",
    "Frisör",
    "Pedofil",
    "Komocka",
    "Cowboy",
    "Shanghai",
    "Ishockeyklubba",
    "Vävstol",
    "Pjäs",
    "Fjäder",
    "Julskinka",
    "Hyrbil",
    "Kurragömma",
    "Is",
    "Alfred",
    "Radio",
    "Bloggare",
    "Albert Einstein",
    "Tjuv",
    "Ben",
    "Tjuv",
    "Reklam",
    "Skolbuss",
    "Helg",
    "Krukväxt",
    "Välling",
    "Kiruna",
    "Curry",
    "Hammare",
    "Sparkcykel",
    "Vespa",
    "Sydafrika",
    "Tjuv",
    "Tjuv",
    "Säd",
    "Vår",
    "Tjuv",
    "Mjölkpall",
    "Kalkon",
    "Bock",
    "Hummer",
    "Kokbok",
    "Stekspade",
    "Bubblepool",
    "Helikopter",
    "Huskvarna",
    "Padda",
    "Polcirkel",
    "Öronsnibb",
    "Mamma",
    "Pappa",
    "Anka",
    "Grisbonde",
    "Stjärngosse",
    "Elefant",
    "Nattmössa",
    "Mamut",
    "Kilt",
    "Varberg",
    "Joggingsko",
    "Farbror",
    "Parfym",
    "Löksås",
    "Glassbil",
    "Tjuv",
    "Tjuv",
    "Matvrak",
    "Backa",
    "Bag in box",
    "Lådvin",
    "Triangel",
    "Husbock",
    "Badboll",
    "Pälsmössa",
    "Frysbox",
    "Nudist",
    "Fattiga riddare",
    "Tramadol",
    "Tjack",
    "Tunnelbana",
    "Snögubbe",
    "Giljotin",
    "Ångmaskin",
    "Zlatan",
    "Tjuv",
    "Reikjavik",
    "Tjuv",
    "Croissant",
    "Ponny",
    "Mugg",
    "Kaka",
    "Tjuv",
    "Tjuv",
    "Tjuv",
    "Gävle",
    "Tårta",
    "Vinterbadare",
    "Ryggsäck",
    "Stämpel",
    "Öresundsbron",
    "Tjuv",
    "Sedel",
    "Våffla",
    "Pensionär",
    "Akvavit",
    "Biltvätt",
    "Tjuv",
    "Sår",
    "Oas",
    "Konstgräs",
    "Boxboll",
    "Underlakan",
    "Tjuv",
    "Pepparkvarn",
    "Estland",
    "Tjuv",
    "Matkasse",
    "Pungråtta",
    "Tjuv",
    "Älg",
    "Fotsvamp",
    "Sotare",
    "Fågelbord",
    "Takfläkt",
    "Vulkan",
    "Harpa",
    "Ormgrop",
    "Gasmask",
    "Pastellfärg",
    "Ketchup",
    "Blixt",
    "Bank",
    "Uppsala",
    "Våg",
    "Blåslampa",
    "Balja",
    "Fjärrkontroll",
    "Casino",
    "Rödluvan",
    "Trollkarl",
    "Mikrofon",
    "Sandal",
    "Hemmafru",
    "Fartkamera",
    "Tjuv",
    "Igelkott",
    "England",
    "Fårskinn",
    "Flygande matta",
    "Ramlösa",
    "Ranch",
    "Tjuv",
    "Slips",
    "Varmluftsugn",
    "Kroppkaka",
    "Ninja",
    "Banan",
    "Pojke",
    "Bacon",
    "Madrass",
    "Räka",
    "Lax",
    "Varg",
    "Väska",
    "Pinne",
    "Lår",
    "Bröst",
    "Flagga",
    "Kändis",
    "Paris",
    "Maräng",
    "Brevlåda",
    "Kantarell",
    "Mekaniker",
    "Präst",
    "Hawaii",
    "Ros",
    "Hjälm",
    "Mecka",
    "Tall",
    "Kristall",
    "Dvärg",
    "Mareld",
    "Advokat",
    "Björn",
    "Häst",
    "Tiger",
    "Korp",
    "Trana",
    "Växthus",
    "Golf",
    "Mandolin",
    "Blåbär",
    "Krusbär",
    "Fort",
    "Smed",
    "Smegma",
    "Palm",
    "Traktor",
    "Biktor",
    "Charlie och lola",
    "Äventyrsdags",
    "Pingu",
    "Bananer i pyjamas",
    "Piff och Puff",
    "Knäckebröd",
    "De tre vännerna och Jerry",
    "Bolibompa",
    "Saul Goodman",
    "Nalle har ett stort blått hus",
    "Järnrör",
    "Invandrare",
    "Mongol",
    "Tillbaks till vintergatan",
    "John Snow",
    "Knäckebröd",
    "Blixten Mcqueen",
    "Lejonkungen",
    "Wall-E",
    "The shining",
    "Pennywise",
    "Anya Taylor-joy",
    "Mario",
    "Shrek",
    "Portal 2",
    "FIFA",
    "Halo",
    "Skyrim",
    "Chris Pratt",
    "Jack Black",
    "Brad Pitt",
    "Michael Jordan",
    "Martin Timell",
    "Kobe Bryant",
    "Bill Cosby",
    "The Rock",
    "Muhammed Ali",
    "Usain Bolt",
    "Tiger Woods",
    "Amy Schumer",
    "James Corden",
    "Björn Borg",
    "Freddy Mercury",
    "Adolf Hitler",
    "David Bowie",
    "Andrew Tate",
    "Chris Rock",
    "Bill Burr",
    "Dave Chapelle",
    "Magnus Betnér",
    "Johan Glans",
    "Per Andersson",
    "Grotesko",
    "Solsidan",
    "Ricky Gervais",
    "Babben Larsson",
    "Henrik Dorsin",
    "Björn Gustafsson",
    "Robert Gustafsson",
    "Harry Styles",
    "Mark Hamill",
    "Tommy Wiesau",
    "Skam",
    "Max Martin",
    "The office",
    "How i met your mother",
    "Riverdale",
    "Ijustwanttobecool",
    "Elon Musk",
    "Mark Zukerber",
    "Rango",
    "Honey Boo Boo",
]

module.exports = {RandomWordsArray};