const Quotes = [
    "I'm 19 years old and my mom still breastfeeds me everyday. She doesn't really have milk or anything anymore, but everyday around 8pm, we snuggle and I suckle for 1-2 hours before she goes to bed. It's always been this way, and I see nothing weird about it. I know it's supposed to be some weird thing so I can't talk about in public. It is a beautiful feeling and a beautiful experience. It doesn't get overly sexual, it's just two humans bonding and I wish society was more accepting of these types of things.",
    `I am attracted to roblox egirls. I don't know why, but when I see their blocky feet I just get excited. I once joined a roblox strip club and when I saw all of those hot roblox avatars, I started drooling. After five minutes of watching the girls twerk, I decided to go into one of those private rooms.

    When I entered, I saw 2 roblox boys passionately kissing eachother. Disgusted by them, I quickly left the game.Later that day, sitting on the toilet, I started seeing things that weren't there. At first I saw a roblox egirl, showing her feet at me. Then, after I tried to lick her legs, I saw those 2 boys again.
    
    I passed out.In the end, I woke up with my head in the toilet. Weirdly, it looked like the toilet got flushed already. What should I do?`,
    `The fuck is it with babes and omelettes? Every time I have a girl over, the next day she wants a fucking omelette. Its gotten so fucking bad that every time I have a date I need to go get condoms, lube, eggs, milk, basil, cherry tomatoes, butter, mushrooms and olive oil. One time I literally said that my pantry was empty just so we could go out for breakfast and she still ordered a fucking omelette. I mentioned it to a couple of friends and they thought I was joking, which shows they’re not getting laid enough because it's happened to me like six times. I’m not sure if their extra X chromosome means they just crave eggs more or something but I’m done with it. If I invite another girl over that wants an omelette I’ll fucking flip, or make toast or something cause I honestly don't care anymore.`,
    `Holy fucking shit. I want to bang the Minecraft Ender Dragon so goddamn bad. I can't stand it anymore. Every time I go to the End I get a massive erection. I've seen literally every rule 34 post there is of her online. My dreams are nothing but .`,
    `I became the first person to cum in 2023

    December 31st 2022 - I sat in my chair furiously masturbating my dick desperate to release gallons of sperm but I resisted the urge and I kept edging for 5 minutes carefully watching the clock on my PC. I waited in anticipation until finally it was 2022. I ejaculated releasing loads and loads of gooey white cum everywhere, I moaned with satisfaction, proud of my achievement.
    
    I had just become the first person to cum in 2023. I look over my cum filled desk and chair with pride.
    
    So all of you can go cry, because none of you will be able to claim my title of first person to cum in 2023. Go wallow in sorrow and self-pity at the fact that you missed the opportunity to ejaculate just when it reached the New Year at midnight. While you subhuman mere mortals are setting of fireworks at midnight, I am blasting a massive explosion of cum everywhere. Oh yes, I am now superior to everyone on the planet, bow down to me, the cum lord of 2023.
    
    Happy new year, losers.`,
    `absolutely hate it when i’m poopin and i just get randomly hard and my tip touches the inside of the bowl 🤢

    like why did toilet inventors have small dicks fr, this issue shouldn’t even exist 😒 #bigdickoppression`,
    `You're probably one of those dudes who walks down the street and everybody looks at him and just yeah, small dick. That's probably who you are. I hope you get really insecure next time you're out in public like, walking down the street and you see someone look at you a little bit and you're like, "oh why are they looking at me? Oh it must just be normal passing traffic" No! Everybody knows. Every girl you meet. Like, when you go talk to a girl in a club. You go "hi my name's Terry" she knows. They all know. I hope you become very insecure because you fucking should be. Everybody whose ever glanced at your pathetic miserable face has known that you have a fucking miniscule penis. And they will for the rest of your life. How does that make you feel?`,
    `英雄联盟 RIP Andrew Tate 1984-2022 英雄联盟 Killed in Romanian Prison 英雄联盟 Alpha Male energgy resulterd in catastropic explosion 英雄联盟 73 dead including defense attorney Joe Rogan 英雄联盟 Heaven gained another angle 英雄联盟 Epstein hitjob rimjob punjabi 1080p 英雄联盟 100% WORKING FREE DOWNLOAD WAREZ ZIP EXE 英雄联盟`,
    `I 16M converted to Judaism last month since all my friends were too, and since we were all uncut we decided to have a group DIY circumcision inside a large stall in the school bathroom, so we grabbed a pair of scissors and we all cut off our foreskin blood is everywhere now so one kid brings out small bandages and we all wrapped them around our manhood. 20 minutes later the bell rings and we all head to class, my class was doing PE and we were doing dancing (We were doing a mauri dance I think) and a girl accidentally hits me while we are dancing and I got a raging boner. the bandage broke and a rush of blood spilled out all over the floor. I was obviously in trouble and got a 2 week suspension when I came back to school I was running all over the school trying to find my snakeskin but couldn't find it, apparently someone in my class grabbed my bloody foreskin and crotched it into a tiny jacket for their pet cockroach. I was outrageous, trying to find out who stole my foreskin. I tried to call the police but the dispatcher would not stop laughing. if anyone sees a cockroach with a light grey jacket on PLEASE take the jacket off and tell me where it is so I can pick it up.`,
    ``,
]